language: node_js
node_js:
  - "8"
env:
  - CI=true
cache:
  directories:
    - "node_modules"
before_install:
  - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] && [ "$TRAVIS_BRANCH" = "master" ]; then TRAVELNEST_PUBLISH="true"; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then TRAVELNEST_TESTRUN="true"; fi'
  - 'if [ "$TRAVELNEST_PUBLISH" = "true" ] || [ $TRAVELNEST_TESTRUN = "true" ]; then TRAVELNEST_INSTALL="true"; fi'
install:
  - 'if [ "$TRAVELNEST_INSTALL" = "true" ]; then npm install; fi'
script:
  - 'if [ "$TRAVELNEST_TESTRUN" = "true" ]; then npm test -- --coverage; fi'
  - 'if [ "$TRAVELNEST_PUBLISH" = "true" ]; then npm test -- --coverage && npm run publish; fi'
deploy: 
  provider: s3
  detect_encoding: true
  cache_control: "max-age=31536000"
  access_key_id: foo
  secret_access_key: bar
  bucket: s3_bucket_name
  skip_cleanup: true
  on:
    branch: master
